services:
  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION:-latest}
    container_name: ${CONTAINER_NAME:-pgadmin4}
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-'False'}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: ${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED:-'False'}
      PGADMIN_DISABLE_POSTFIX: ${PGADMIN_DISABLE_POSTFIX:-'True'}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - ${VOLUME_NAME:-pgadmin4_data}:/var/lib/pgadmin
    networks:
      - postgres_network_dev
      - postgres_network_prod
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgadmin4_data:
    driver: local
    name: ${VOLUME_NAME:-pgadmin4_data}

networks:
  postgres_network_dev:
    external: true
    name: postgres_network_dev
  postgres_network_prod:
    external: true
    name: postgres_network_prod
